services:
  postgresql:
    image: postgres:17
    container_name: postgres_db
    restart: always
    secrets:
      - db-password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./core
      dockerfile: dev.Dockerfile
    volumes:
      - ./.docker/aws:/aws:ro
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - AWS_PROFILE=pastebin
      - AWS_CONFIG_FILE=/aws/config
      - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
    develop:
      watch:
        - path: ./core
          action: rebuild
    depends_on:
      postgresql:
        condition: service_healthy
    secrets:
      - db-password

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - '5173:5173'
    environment:
      - VITE_BACKEND_HOST=localhost
      - VITE_BACKEND_PORT=8000
    develop:
      watch:
        - path: ./frontend
          action: rebuild
    depends_on:
      backend:
        condition: service_started

volumes:
  pg-data:
secrets:
  db-password:
    file: ./core/secrets/postgresql/credential
