name: Feature Push Tests

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
    paths:
      - core/**
      - frontend/**
      - compose.yaml

  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Set up UV
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          version: "0.11.18"
          python-version: "3.12"

      - name: Install backend dependencies
        working-directory: core
        run: uv sync --frozen

      - name: Create test database credential
        run: |
          mkdir -p core/secrets/postgresql
          echo "test-password" > core/secrets/postgresql/credential

      - name: Test linting
        working-directory: core
        run: uv run ruff check .

      - name: Unit Tests
        working-directory: core
        run: uv run pytest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@ecf28ddc73e819eb6fa29df6b34ef8921c743461

      - name: Install frontend dependencies
        working-directory: frontend
        run: bun install --frozen-lockfile

      - name: Run frontend tests
        working-directory: frontend
        run: bun run test

      - name: Build frontend dependencies
        working-directory: frontend
        run: bun run build
