name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      frontend--tag_name: ${{ steps.release.outputs.frontend--tag_name}}
      frontend--release_created: ${{ steps.release.outputs.frontend--release_created}}
      core--tag_name: ${{ steps.release.outputs.core--tag_name}}
      core--release_created: ${{ steps.release.outputs.core--release_created}}
    steps:
      - name: Create Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Print Release Info
        continue-on-error: true
        run: |
            echo "Release outputs:"
            echo "${{ toJson(steps.release.outputs) }}"

      - name: Trigger Frontend Image Build
        if: steps.release.outputs.frontend--release_created == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-images.yml',
              ref: 'main',
              inputs: {
                component: 'frontend',
                version: '${{ steps.release.outputs.frontend--tag_name }}',
              },
            });

      - name: Trigger Core Image Build
        if: steps.release.outputs.core--release_created == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-images.yml',
              ref: 'main',
              inputs: {
                component: 'core',
                version: '${{ steps.release.outputs.core--tag_name }}',
              },
            });
